export const ROUTES = {
  ADMIN: "/admin",
  ADMINITEMDETAIL: "item_details",
  ADDPRODUCT: "add-product",
  SETTINGPRICEQUANTITYITEM: "setting-price-quantity-item",
  DESCRIPTIONOVERVIEW: "description-overview",
  MAIN: "/",
  ABOUTSTORE: "/about",
  PHONE: ":catalogItem",
  PRODUCT: ":product",
  ORDERING: "ordering",
  CART: "cart",
  CHECKOUT: "checkout",
  COMPATISONPRODUCT: "comporative",
  LIKE: "favorite",
  DELIVERY: "delivery",
  FAG: "fag",
  CONTACTS: "contacts",
  VIP: "/vip",
  HISTORY: "history",
  GOODS: "goods",
  ORDERS: "orders",
  REVIEWSRATING: "reviews-rating",
  SIGNIN: "/sign-in",
  SIGNUP: "/sign-up",
  NOTFOUND: "/*",
  PROFILE: "profile",
};
